ekf_filter_node:
  ros__parameters:
    use_sim_time: false
    frequency: 15.0
    sensor_timeout: 0.5
    two_d_mode: false
    
    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    publish_tf: true

    odom0: /odometry/gps
    odom0_config: [true, true,  true,  # x, y
                   false, false, true,  # Orientation
                   true, true, false,  # Velocity
                   false, false, true,  # Angular velocity
                   false, false, false]  # Acceleration
    odom0_differential: false

    imu0: /drone_imu
    imu0_config: [false, false, false,
                  true, true, true,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    imu0_differential: false

    odom1: /rf_distance_odom
    odom1_config: [false, false, true,   # only z
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom1_differential: false
