ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.5
    transform_timeout: 0.2
    two_d_mode: false

    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom   # safer if no global map frame

    imu0: /drone_imu
    imu0_config: [false, false, false,
                  true,  true,  true,   
                  false, false, false,  
                  false, false, false]  
 
    imu0_queue_size: 10
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true

    rf_distance0: /rf_distance
    rf_distance0_config: [false, false, true,  # Z position only
                          false, false, false, # no orientation
                          false, false, false, # no linear velocity
                          false, false, false] # no linear acceleration

    rf_distance0_queue_size: 10