navsat_transform_node:
  ros__parameters:
    frequency: 5.0

    # Frames
    gps_frame: gps
  
    # Topics
    gps_topic: /gps/fix
    odometry_topic: /odometry/filtered

    use_odometry_yaw: true
    zero_altitude: true
    broadcast_cartesian_transform: true  # <-- Updated line
    publish_filtered_gps: true

    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
